---
title: "New clustering of us"
author: "Tanfu Shi"
date: "2024-06-17"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

new data set
```{r}
library(mclust)
library(tidyLPA)
library(tidyverse)
library(haven)
library(stats)
set.seed(100)
combined_data<-read_sav("C:/Users/14946/Downloads/Midus1&2Merge_Squad_Wellbeing_Tanfu_Data_new.sav")
us_data<-read_sav("C:/Users/14946/Downloads/Midus1&2Merge_Squad_Wellbeing_Tanfu_Data.sav")
US_new_data<-read_sav("C:/Users/14946/Downloads/Midus1&2Merge_Squad_Wellbeing_Tanfu_Data.sav")%>%
  select(M2ID,ZTotalSocialAffectualSolidarity,ZMyMidus1Autonomy,ZTotalSocialAffectualSolidarityW2,ZMyMidus2Autonomy)%>%
  na.omit()
Midus1_Squad_Data_USJAPANwellbeing<-read_sav("C:/Users/14946/Downloads/Midus1_Squad_Data_USJAPANwellbeing.sav")

```
Kmeans
```{r}
set.seed(100) 
cluster_old<-US_new_data%>%
  select(ZTotalSocialAffectualSolidarity,ZMyMidus1Autonomy)%>%
  kmeans(centers = 4, nstart = 25)
set.seed(100) 
cluster_new<-US_new_data%>%
  select(ZTotalSocialAffectualSolidarityW2,ZMyMidus2Autonomy)%>%
  kmeans(centers = 4, nstart = 25)
US_new_data$cluster_old<-cluster_old$cluster
US_new_data$cluster_new<-cluster_new$cluster
```

plot
```{r}
data_old <- US_new_data %>%
  mutate(cluster_old = case_when(
    cluster_old == 1 ~ "Q1",
    cluster_old == 2 ~ "Q2",
    cluster_old == 3 ~ "Q3",
    cluster_old == 4 ~ "Q4",
    TRUE ~ as.character(cluster_old)
  ))
data_old$cluster_old <- as.factor(data_old$cluster_old)
ggplot(data_old, aes(x = ZTotalSocialAffectualSolidarity, y = ZMyMidus1Autonomy, color = cluster_old)) +
  geom_point(size = 1) +
  geom_jitter(width = 0.1, height = 0.1) +  
  labs(x = "Communion", y = "Autonomy", title = "Cluster Analysis in the US OLD data") +
  scale_color_manual(values = c("Q1" = "red", "Q2" = "green", "Q3" = "blue", "Q4" = "purple")) +
  theme_gray() +  
  theme(
    plot.title = element_text(face = "bold", color = "#333333"),
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "#EBEBEB"),
    legend.background = element_rect(fill = "white"),
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 12)
  )  +
  scale_x_continuous(limits = c(-4, 4)) + 
  scale_y_continuous(limits = c(-4, 4))   
```
new data
```{r}
data_new <- US_new_data %>%
  mutate(cluster_new = case_when(
    cluster_new  == 1 ~ "Q3",
    cluster_new  == 2 ~ "Q1",
    cluster_new  == 3 ~ "Q4",
    cluster_new  == 4 ~ "Q2",
    TRUE ~ as.character(cluster_new )
  ))
data_new$cluster_new  <- as.factor(data_new$cluster_new )
ggplot(data_new, aes(x = ZTotalSocialAffectualSolidarityW2, y = ZMyMidus2Autonomy, color = cluster_new )) +
  geom_point(size = 1) +
  geom_jitter(width = 0.1, height = 0.1) +  
  labs(x = "Communion", y = "Autonomy", title = "Cluster Analysis in the US new data") +
  scale_color_manual(values = c("Q1" = "red", "Q2" = "green", "Q3" = "blue", "Q4" = "purple")) +
  theme_gray() +  
  theme(
    plot.title = element_text(face = "bold", color = "#333333"),
    plot.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = "#EBEBEB"),
    legend.background = element_rect(fill = "white"),
    legend.title = element_text(face = "bold"),
    legend.text = element_text(size = 12)
  )  +
  scale_x_continuous(limits = c(-4, 4)) + 
  scale_y_continuous(limits = c(-4, 4))   
```
data clean
```{r}
library(ggalluvial)
data<-merge(data_new, data_old, by = "M2ID")
sankey_data <- data %>%
  count(cluster_old.y, cluster_new.x)

# 绘制桑基图显示聚类变化
ggplot(sankey_data, aes(axis1 = factor(cluster_old.y), axis2 = factor(cluster_new.x), y = n)) +
  geom_alluvium(aes(fill = factor(cluster_old.y)), width = 1/12) +
  geom_stratum(width = 1/12, fill = "grey") +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  labs(x = "Time", y = "Number of Observations",
       title = "Sankey Diagram of Cluster Changes") +
  scale_x_discrete(limits = c("Old Cluster", "New Cluster")) +
  theme_minimal()
```

```{r}
heatmap_data <- data %>%
  count(cluster_old.y, cluster_new.x)

# 热力图
heatmap_data <- data %>%
  count(cluster_old.y, cluster_new.x) %>%
  group_by(cluster_old.y) %>%
  mutate(percentage = n / sum(n) * 100)

# 绘制热力图并添加百分比标注
heatmap_plot <- ggplot(heatmap_data, aes(x = factor(cluster_old.y), y = factor(cluster_new.x), fill = percentage)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), color = "black", size = 3) +
  scale_fill_gradient(low = "white", high = "blue", name = "Percentage") +
  labs(x = "Old Cluster", y = "New Cluster", title = "Heatmap of Cluster Changes Over Time") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

heatmap_plot
```
```{r}
library(GGally)

barplot_data <- data %>%
  count(cluster_old.y, cluster_new.x)

# 绘制分组条形图
ggplot(barplot_data, aes(x = factor(cluster_old.y), y = n, fill = factor(cluster_new.x))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Old Cluster", y = "Count", fill = "New Cluster",
       title = "Grouped Bar Plot of Cluster Changes Over Time") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
score change 
```{r}
data_5<-combined_data%>%
  select(M2ID,A1SSATIS,B1SSATIS,posMINUSnegaffectMIDUS1,posMINUSnegaffectMIDUS2,A1SPWBG,A1SPWBU,A1SPWBS,B1SPWBG1,B1SPWBU1,B1SPWBS1)
data_score<-inner_join(data,data_5,by="M2ID")
data_score$change <- paste(data_score$cluster_old.y, data_score$cluster_new.x, sep = "_to_")
change_distribution <- data_score %>%
  group_by(change) %>%
  summarise(count = n())

```
split
life satisfaction
```{r}
data_score_split <- data_score %>%
  split(.$change)
file_dir <- "C:/Users/14946/Documents/plots/"

if (!dir.exists(file_dir)) {
  dir.create(file_dir)
}

for (i in 1:length(data_score_split)) {
  change_name <- names(data_score_split)[i]
  LIFEchange <- (data_score_split[[i]]$B1SSATIS - data_score_split[[i]]$A1SSATIS) / nrow(data_score_split[[i]])
  temp_df <- data.frame(LIFEchange = LIFEchange)

  t_test_result <- t.test(data_score_split[[i]]$A1SSATIS, data_score_split[[i]]$B1SSATIS, paired = TRUE)
  print(change_name)
  print(t_test_result)
  median_value <- median(temp_df$LIFEchange, na.rm = TRUE)
  mean_value <- mean(temp_df$LIFEchange, na.rm = TRUE)
  
  p <- ggplot(temp_df, aes(x = "", y = LIFEchange)) +
    geom_boxplot() +
    geom_jitter(width = 0.2, alpha = 0.6, color = "blue") +
    geom_text(aes(x = "", y = median_value, label = sprintf("Median: %.4f", median_value)), vjust = -1.5, size = 4, color = "brown") +
    geom_text(aes(x = "", y = mean_value, label = sprintf("Mean: %.4f", mean_value)), vjust = 1.5, size = 4, color = "red") +
    labs(title = paste("LIFE Expectation for", change_name),
         x = change_name,
         y = "LIFE Expectation") +
    theme_minimal() +
    theme(axis.text.x = element_blank())
  
  print(p)
  file_path <- paste0(file_dir, "plot_", i, ".png")
  ggsave(filename = file_path, plot = p, width = 8, height = 6, dpi = 300)
}
```
posMINUSnegaffect
```{r}
for (i in 1:length(data_score_split)) {
  change_name <- names(data_score_split)[i]
  LIFEchange <- (data_score_split[[i]]$posMINUSnegaffectMIDUS2 - data_score_split[[i]]$posMINUSnegaffectMIDUS1) / nrow(data_score_split[[i]])
  temp_df <- data.frame(LIFEchange = LIFEchange)
  
  t_test_result <- t.test(data_score_split[[i]]$posMINUSnegaffectMIDUS1, data_score_split[[i]]$posMINUSnegaffectMIDUS2, paired = TRUE)
  print(change_name)
  print(t_test_result)
  median_value <- median(temp_df$LIFEchange, na.rm = TRUE)
  mean_value <- mean(temp_df$LIFEchange, na.rm = TRUE)
  
  p <- ggplot(temp_df, aes(x = "", y = LIFEchange)) +
    geom_boxplot() +
    geom_jitter(width = 0.2, alpha = 0.6, color = "blue") +
    
    geom_text(aes(x = "", y = median_value, label = sprintf("Median: %.4f", median_value)), 
              vjust = -1.5, size = 4, color = "brown", hjust = 0.5) +
    
    geom_text(aes(x = "", y = mean_value, label = sprintf("Mean: %.4f", mean_value)), 
              vjust = -3, size = 4, color = "red", hjust = 0.5) +
    
    labs(title = paste("posMINUSnegaffect for", change_name),
         x = change_name,
         y = "posMINUSnegaffect") +
    theme_minimal() +
    theme(axis.text.x = element_blank())
  
  print(p)
  file_path <- paste0(file_dir, "1plot_", i, ".png")
  ggsave(filename = file_path, plot = p, width = 8, height = 6, dpi = 300)
}
```
Personal Growth
```{r}
for (i in 1:length(data_score_split)) {
  change_name <- names(data_score_split)[i]
  LIFEchange <- (data_score_split[[i]]$B1SPWBG1 - data_score_split[[i]]$A1SPWBG ) / nrow(data_score_split[[i]])
  temp_df <- data.frame(LIFEchange = LIFEchange)
  
  t_test_result <- t.test(data_score_split[[i]]$A1SPWBG, data_score_split[[i]]$B1SPWBG1, paired = TRUE)
  print(change_name)
  print(t_test_result)
  median_value <- median(temp_df$LIFEchange, na.rm = TRUE)
  mean_value <- mean(temp_df$LIFEchange, na.rm = TRUE)
  
  p <- ggplot(temp_df, aes(x = "", y = LIFEchange)) +
    geom_boxplot() +
    geom_jitter(width = 0.2, alpha = 0.6, color = "blue") +
    
    geom_text(aes(x = "", y = median_value, label = sprintf("Median: %.4f", median_value)), 
              vjust = -1.5, size = 4, color = "brown", hjust = 0.5) +
    
    geom_text(aes(x = "", y = mean_value, label = sprintf("Mean: %.4f", mean_value)), 
              vjust = -3, size = 4, color = "red", hjust = 0.5) +
    
    labs(title = paste("Personal Growth for", change_name),
         x = change_name,
         y = "Personal Growth") +
    theme_minimal() +
    theme(axis.text.x = element_blank())
  
  print(p)
  file_path <- paste0(file_dir, "2plot_", i, ".png")
  ggsave(filename = file_path, plot = p, width = 8, height = 6, dpi = 300)
}
```
Purpose in life
```{r}
for (i in 1:length(data_score_split)) {
  change_name <- names(data_score_split)[i]
  LIFEchange <- (data_score_split[[i]]$B1SPWBU1
 - data_score_split[[i]]$A1SPWBU ) / nrow(data_score_split[[i]])
  temp_df <- data.frame(LIFEchange = LIFEchange)
  
  t_test_result <- t.test(data_score_split[[i]]$A1SPWBU, data_score_split[[i]]$B1SPWBU1, paired = TRUE)
  print(change_name)
  print(t_test_result)
  median_value <- median(temp_df$LIFEchange, na.rm = TRUE)
  mean_value <- mean(temp_df$LIFEchange, na.rm = TRUE)
  
  p <- ggplot(temp_df, aes(x = "", y = LIFEchange)) +
    geom_boxplot() +
    geom_jitter(width = 0.2, alpha = 0.6, color = "blue") +
    
    geom_text(aes(x = "", y = median_value, label = sprintf("Median: %.4f", median_value)), 
              vjust = -1.5, size = 4, color = "brown", hjust = 0.5) +
    
    geom_text(aes(x = "", y = mean_value, label = sprintf("Mean: %.4f", mean_value)), 
              vjust = -3, size = 4, color = "red", hjust = 0.5) +
    
    labs(title = paste("Purpose in life for", change_name),
         x = change_name,
         y = "Purpose in life") +
    theme_minimal() +
    theme(axis.text.x = element_blank())
  
  print(p)
  file_path <- paste0(file_dir, "3plot_", i, ".png")
  ggsave(filename = file_path, plot = p, width = 8, height = 6, dpi = 300)
}
```




Self Acceptance
```{r}
for (i in 1:length(data_score_split)) {
  change_name <- names(data_score_split)[i]
  LIFEchange <- (data_score_split[[i]]$B1SPWBS1
 - data_score_split[[i]]$A1SPWBS ) / nrow(data_score_split[[i]])
  temp_df <- data.frame(LIFEchange = LIFEchange)
  
  t_test_result <- t.test(data_score_split[[i]]$A1SPWBS, data_score_split[[i]]$B1SPWBS1, paired = TRUE)
  print(change_name)
  print(t_test_result)
  median_value <- median(temp_df$LIFEchange, na.rm = TRUE)
  mean_value <- mean(temp_df$LIFEchange, na.rm = TRUE)
  
  p <- ggplot(temp_df, aes(x = "", y = LIFEchange)) +
    geom_boxplot() +
    geom_jitter(width = 0.2, alpha = 0.6, color = "blue") +
    
    geom_text(aes(x = "", y = median_value, label = sprintf("Median: %.4f", median_value)), 
              vjust = -1.5, size = 4, color = "brown", hjust = 0.5) +
    
    geom_text(aes(x = "", y = mean_value, label = sprintf("Mean: %.4f", mean_value)), 
              vjust = -3, size = 4, color = "red", hjust = 0.5) +
    
    labs(title = paste("Self Acceptance for", change_name),
         x = change_name,
         y = "Self Acceptance") +
    theme_minimal() +
    theme(axis.text.x = element_blank())
  
  print(p)
  file_path <- paste0(file_dir, "4plot_", i, ".png")
  ggsave(filename = file_path, plot = p, width = 8, height = 6, dpi = 300)
}
```